name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "此问题已过时，因为它已打开30天，没有任何活动。如该问题仍未解决，请提供更多信息。"
          close-issue-message: "此问题已关闭，因为自标记为过时以来，它已处于非活动状态14天。"
          days-before-pr-stale: -1
          days-before-pr-close: -1
          only-labels: "question"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
